---
- name: ant
  hosts: all
  tasks: 
  - name: kopiowanie propertisow {{ env }}
    command: "{{item}}"
    with_items: 
    - cp -f /opt/DOCKER/WGRANIA/{{ env }}/properties/build.properties /opt/DOCKER/WGRANIA/def3000_UF_{{ var }}/db
  - name: ant
    shell: ant -buildfile /opt/DOCKER/WGRANIA/def3000_UF_{{ var }}/db/build.xml
    register: ant
  - debug: var=ant.stdout_lines
