---
- name: Up Up Up my little container
  hosts: all
  tasks:
  - name: remove container
    docker_container:
      name: wer_{{ env }}_{{ var }}
      state: absent
  - name: up container wer_{{ env }}_{{ var }}
    docker:
      name: wer_{{ env }}_{{ var }}
      image: localhost:5000/uf/wls1036j6ufdb:1.3
      state: started
      volumes:
      - /opt/DOCKER:/DEPLOY 
      ports:
      - "{{ port_consola }}:7001"
      - "{{ port_app }}:7011"
      - "{{ port_debug }}:4000"