---
- name: Up Up Up my little container
  hosts: all
  tasks:
  - name: remove container
    docker_container:
      name: wer_{{ env }}_{{ var }}
      state: absent
  - name: up container wer_{{ env }}_{{ var }}
    docker_container:
      name: wer_{{ env }}_{{ var }}
      image: localhost:5000/uf/wls1036j6ufdb:1.3
      state: started
      volumes:
      - /opt/DOCKER:/DEPLOY 
      ports:
      - "{{ port_consola }}:7001"
      - "{{ port_app }}:7011"
      - "{{ port_debug }}:4000"
    when: (env == "UFDB_t") or (env == "UFDB_p") or (env == "UFDB_r") or (env == "UFTOYOTA_t") or (env == "UFTOYOTA_p") or (env == "UFTOYOTA_r")
  - name: up container wer_{{ env }}_{{ var }}
    docker_container:
      name: wer_{{ env }}_{{ var }}
      image: localhost:5000/uf/was7j6ufbos:1.4ap
      state: started
      #command: a2enmod proxy proxy_http && service apache2 restart
      networks: 
        - name: siecDocker
          ipv4_address: "{{ ip_auth }}"
      volumes:
      - /opt/DOCKER:/DEPLOY 
      ports:
      - "{{ port_consola }}:9043"
      - "{{ port_app }}:{{ port_app }}"
      - "{{ port_debug }}:7777"
    when: (env == "UFBOS_p") or (env == "UFBOS_t") or (env == "UFBOS_r")
