---
- name: instalowanie aplikacji
  hosts: all
  tasks: 
  - name: bash WAS {{ var }} {{ env}}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i '1s/sh/bash/' /opt/IBM/WebSphere/AppServer/bin/wsadmin.sh'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFGROCK_p" or env == "UFGROCK_r" or env == "UFGROCK_t" 
  - name: update apache-conf {{ var }} {{ env }}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i '1s/9088/{{ port_app }}/' /etc/apache2/sites-enabled/ufsgb.conf'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFGROCK_p" or env == "UFGROCK_r" or env == "UFGROCK_t"   
  - name: update apache-port {{ var }} {{ env }}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i 's/9088/{{ port_app }}/' /etc/apache2/ports.conf'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFGROCK_p" or env == "UFGROCK_r" or env == "UFGROCK_t"
  - name: update ip {{ var }} {{ env }}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i 's/172.18.0.28/{{ ip_auth }}/' /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/UFcfg.properties'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t"   
  - name: update data source, ear, start WAS {{ var }} UFBOS_p
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'cd /DEPLOY/WGRANIA/UFBOS_p/properties/AUTOMAT && sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/wsadmin.sh -lang jython -f UF_deploy2.py def3000_UF_{{ var }}'
    when: env == "UFBOS_p"
  - name: update data source, ear, start WAS {{ var }} UFBOS_r
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'cd /DEPLOY/WGRANIA/UFBOS_r/properties/AUTOMAT && sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/wsadmin.sh -lang jython -f UF_deploy2.py def3000_UF_{{ var }}'
    when: env == "UFBOS_r"
  - name: update data source, ear, start WAS {{ var }} UFBOS_t
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'cd /DEPLOY/WGRANIA/UFBOS_t/properties/AUTOMAT && sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/wsadmin.sh -lang jython -f UF_deploy2.py def3000_UF_{{ var }}'    
    when: env == "UFBOS_t"
  - name: update data source, ear, start WAS {{ var }} UFGROCK_r
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'cd /DEPLOY/WGRANIA/UFGROCK_r/properties/AUTOMAT && sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/wsadmin.sh -lang jython -f UF_deploy2.py def3000_UF_{{ var }}'    
    when: env == "UFGROCK_r"   
  - name: rm apache pid
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'rm -f /var/run/apache2/apache2.pid'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFGROCK_p" or env == "UFGROCK_r" or env == "UFGROCK_t" 
  - name: start apache
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'a2enmod proxy proxy_http && service apache2 restart'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFGROCK_p" or env == "UFGROCK_r" or env == "UFGROCK_t"
  - name: restart WAS
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/stopServer.sh server1 && nohup sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/startServer.sh server1&'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFGROCK_p" or env == "UFGROCK_r" or env == "UFGROCK_t"

    
   