---
- name: instalowanie aplikacji
  hosts: all
  tasks: 
  - name: bash WAS {{ var }} {{ env}}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i '1s/sh/bash/' /opt/IBM/WebSphere/AppServer/bin/wsadmin.sh'
  - name: update apache-conf {{ var }} {{ env }}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i '1s/9088/{{ port_app }}/' /etc/apache2/sites-enabled/ufsgb.conf'  
  - name: update apache-port {{ var }} {{ env }}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i 's/9088/{{ port_app }}/' /etc/apache2/ports.conf'
  - name: update ip {{ var }} {{ env }}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i 's/172.18.0.28/{{ ip_auth }}/' /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/UFcfg.properties'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFBOS_x"
  - name: update path template {{ var }} {{ env }}
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sed -i '33iparameter.jasper.report_path=/opt/IBM/WebSphere/AppServer/applib/uf/templates/' /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/UFcfg.properties'
    when: env == "UFBOS_p" or env == "UFBOS_r" or env == "UFBOS_t" or env == "UFBOS_x"    
  - name: update data source, ear, start WAS {{ var }} 
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'cd /DEPLOY/WGRANIA/{{ env }}/properties/AUTOMAT && sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/wsadmin.sh -lang jython -f UF_deploy2.py def3000_UF_{{ var }}'
  - name: rm apache pid
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'rm -f /var/run/apache2/apache2.pid'
  - name: start apache
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'a2enmod proxy proxy_http && service apache2 restart'
  - name: restart WAS
    shell: docker exec -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/stopServer.sh server1 && nohup sh /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/startServer.sh server1&'

    
   