---
- name: updateDS
  hosts: all
  tasks: 
  - name: wait_for http 
    pause:
      seconds: 60
  - name: update data source {{ var }} UFDB_r
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /DEPLOY/WGRANIA/UFDB_r/properties/UF_datasource.bash'
    when: env == "UFDB_r"
  - debug:
    msg: "update datasourcow dla srodowiska {{ env }}"   
  - name: update data source {{ var }} UFDB_t
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /DEPLOY/WGRANIA/UFDB_t/properties/UF_datasource.bash'
    when: env == "UFDB_t"
  - debug:
    msg: "update datasourcow dla srodowiska {{ env }}"   
  - name: update data source {{ var }} UFDB_p
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /DEPLOY/WGRANIA/UFDB_p/properties/UF_datasource.bash'
    when: env == "UFDB_p"  
  - debug:
    msg: "update datasourcow dla srodowiska {{ env }}"
  - name: update data source {{ var }} UFTOYOTA_r
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /DEPLOY/WGRANIA/UFTOYOTA_r/properties/UF_datasource.bash'
    when: env == "UFTOYOTA_r"
  - debug:
    msg: "update datasourcow dla srodowiska {{ env }}"
  - name: update data source {{ var }} UFTOYOTA_p
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /DEPLOY/WGRANIA/UFTOYOTA_p/properties/UF_datasource.bash'
    when: env == "UFTOYOTA_p"
  - debug:
    msg: "update datasourcow dla srodowiska {{ env }}"
  - name: update data source {{ var }} UFTOYOTA_t
    shell: docker exec -d -u 0 wer_{{ env }}_{{ var }} sh -c 'sh /DEPLOY/WGRANIA/UFTOYOTA_t/properties/UF_datasource.bash'
    when: env == "UFTOYOTA_t"
  - debug:
    msg: "update datasourcow dla srodowiska {{ env }}"    
